- AI:
    - Enables machines and computers to simulate human learning, problem solving, decision making, etc.,
    - They can make detailed recommendations to users and experts.
    - They can act independently, replacing the need for human intelligence or intervention.
    - To fully understand generative AI, it’s important to first understand the technologies on which generative AI tools are built
    - machine learning (ML) and deep learning (DL).
    - 1950:
        - Alan Turing publishes Computing Machinery and Intelligence (link resides outside ibm.com).
        - In this paper, Turing—famous for breaking the German ENIGMA code during WWII and often referred to as the "father of computer science".
        - Asks the following question:Can machines think?
        - From there, he offers a test, now famously known as the "Turing Test," where a human interrogator would try to distinguish between a computer and human text response.
        - While this test has undergone much scrutiny since it was published, it remains an important part of the history of AI, and an ongoing concept within philosophy as it uses ideas around linguistics.
    - 1956:
        - John McCarthy coins the term "artificial intelligence" at the first-ever AI conference at Dartmouth College.
        - McCarthy went on to invent the Lisp language.
        - Later that year, Allen Newell, J.C. Shaw and Herbert Simon create the Logic Theorist, the first-ever running AI computer program.
    - 1967:
        - Frank Rosenblatt builds the Mark 1 Perceptron, the first computer based on a neural network that "learned" through trial and error.
        - Just a year later, Marvin Minsky and Seymour Papert publish a book titled Perceptrons, which becomes both the landmark work on neural networks and, at least for a while, an argument against future neural network research initiatives.
    - 1980:
        - Neural networks, which use a backpropagation algorithm to train itself, became widely used in AI applications.
    - 1995:
        - Stuart Russell and Peter Norvig publish Artificial Intelligence
        - A Modern Approach (link resides outside ibm.com), which becomes one of the leading textbooks in the study of AI.
        - In it, they delve into four potential goals or definitions of AI, which differentiates computer systems based on rationality and thinking versus acting.
    - 1997:
        - IBM's Deep Blue beats then world chess champion Garry Kasparov, in a chess match (and rematch).
